// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATw5_MEtVdqYIbB_9kgxUyDI8YrLizk34',
    appId: '1:775147301180:web:a64fe3c43d7102e958d639',
    messagingSenderId: '775147301180',
    projectId: 'todolist13-7f2fc',
    authDomain: 'todolist13-7f2fc.firebaseapp.com',
    storageBucket: 'todolist13-7f2fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQIphVHiFAZ-H8YTx8DdXHy5mMlGomuM',
    appId: '1:775147301180:android:c2731001d27a34b758d639',
    messagingSenderId: '775147301180',
    projectId: 'todolist13-7f2fc',
    storageBucket: 'todolist13-7f2fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2cVaDYYVtoPyXysLwEMqcRuCtEMONHkc',
    appId: '1:775147301180:ios:24c7102fa441cd7158d639',
    messagingSenderId: '775147301180',
    projectId: 'todolist13-7f2fc',
    storageBucket: 'todolist13-7f2fc.appspot.com',
    iosBundleId: 'com.example.todolistflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2cVaDYYVtoPyXysLwEMqcRuCtEMONHkc',
    appId: '1:775147301180:ios:5b684890e9ee630458d639',
    messagingSenderId: '775147301180',
    projectId: 'todolist13-7f2fc',
    storageBucket: 'todolist13-7f2fc.appspot.com',
    iosBundleId: 'com.example.todolistflutterapp.RunnerTests',
  );
}
